In [17]:
import numpy as np

In [18]:
arr = np.arange(1, 11)

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Operation

In [21]:
arr[arr%2 == 0]

array([ 2,  4,  6,  8, 10])

# How

In [22]:
arr%2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [23]:
arr[np.array([False,  True, False,  True, False,  True, False,  True, False,
        True])]

array([ 2,  4,  6,  8, 10])

# Boolean numpy array of same size of any numpy array inside variable creates a new array by returning array actual values ehich indexes of boolean holding True value

In [24]:
arr[np.array([True,  True, False,  False, False,  True, False,  True, False,
        True])]

array([ 1,  2,  6,  8, 10])

In [25]:
np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])[np.array([True,  True, False,  False, False,  True, False,  True, False,
        True])]

array([ 1,  2,  6,  8, 10])

In [28]:
np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])[0]

1

In [29]:
l = [1,2,3]

In [30]:
l[[1,2]]

TypeError: list indices must be integers or slices, not list

# Hence It can concluded that multiple or different index values can be accessed  in numpy array according user requirements (based or boolean array passing as index in [ ] operator )unlike normal list where one index value or typical range by slice opertor can be accessed 