# Exercise file for numpy

In [3]:
myList = [1, 2, 3, 4, 5]

In [4]:
myList

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [6]:
np.array(myList)

array([1, 2, 3, 4, 5])

In [7]:
LinearArray = np.array(myList)

In [8]:
LinearArray

array([1, 2, 3, 4, 5])

In [9]:
TwoDimArr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
TwoDimArr

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
MultiArray = np.array(TwoDimArr)

In [14]:
MultiArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0, 10, 8)

array([0, 8])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.zeros((4, 5)).astype("int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [37]:
np.zeros((4, 5)).astype("char")

TypeError: data type "char" not understood

In [38]:
l = [1, 2, "sushant"]

In [39]:
lnp = np.array(l)

In [40]:
lnp

array(['1', '2', 'sushant'], dtype='<U11')

In [41]:
l.pop()

'sushant'

In [42]:
lnp

array(['1', '2', 'sushant'], dtype='<U11')

In [43]:
lnp = np.array(l)

In [44]:
lnp

array([1, 2])

In [45]:
l = [[1,"squad"], [2, 3], [4, 5]]

In [46]:
l


[[1, 'squad'], [2, 3], [4, 5]]

In [47]:
lnp = np.array(l)

In [48]:
lnp

array([['1', 'squad'],
       ['2', '3'],
       ['4', '5']], dtype='<U11')

In [49]:
np.arange(3)

array([0, 1, 2])

In [56]:
np.arange(0, 3,\
          2)

array([0, 2])

In [59]:
np.ones([2,3]).astype("int")

array([[1, 1, 1],
       [1, 1, 1]])

In [69]:
np.ones((2, 3), dtype = "int", order ="C")

array([[1, 1, 1],
       [1, 1, 1]])

# Get a Matrix of all ones 3, 4

In [71]:
np.ones((3, 4), dtype = "int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.linspace(0, 5, 3)

array([0. , 2.5, 5. ])

In [17]:
np.arange(0, 5, 4)

array([0, 4])

In [21]:
np.identity(4, dtype="int")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [29]:
np.random.rand(3, 4)

array([[0.01258373, 0.92138798, 0.96964362, 0.89681766],
       [0.51730656, 0.3997949 , 0.17493777, 0.58903604],
       [0.49001597, 0.36202803, 0.1130793 , 0.02005736]])

In [30]:
np.random.randn(3, 4)

array([[-0.61778412,  0.48558645,  0.2311627 , -0.98209441],
       [-0.38475493, -0.31970055, -0.06963983, -0.02444415],
       [ 0.12239357, -0.16469957,  0.51757138,  0.08957094]])

In [37]:
np.random.randint(1, 978)

105

In [38]:
myNum = np.arange(25)

In [39]:
myNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [56]:
myReshaped = myNum.reshape(5, 5)

In [57]:
myReshaped

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
myReshaped.argmin()

0

In [1]:
pwd

'C:\\Users\\sushant\\Desktop\\ML\\Numpy'