https://docs.scipy.org/doc/numpy/reference/generated/numpy.cross.html?highlight=numpy%20cross#numpy.cross

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3])

In [4]:
a

array([1, 2, 3])

In [5]:
b = np.array([4, 5, 6])

In [6]:
b

array([4, 5, 6])

In [8]:
np.cross(a, b)

array([-3,  6, -3])

In [9]:
np.cross(a, b, axisa = 0)

array([-3,  6, -3])

In [10]:
np.cross(a, b, axisb = 0)

array([-3,  6, -3])

In [11]:
np.cross(a, b, axisc = 0)

array([-3,  6, -3])

In [12]:
np.cross(a, b, axis = 0)

array([-3,  6, -3])

In [13]:
c = np.array([4, 5])

In [14]:
c

array([4, 5])

In [18]:
a

array([1, 2, 3])

In [20]:
np.cross(a, c)

array([-15,  12,  -3])

In [21]:
np.cross(a, c, axisa = 0)

array([-15,  12,  -3])

In [24]:
np.cross(a, c, axisb = 0)

array([-15,  12,  -3])

In [25]:
np.cross(a, c, axisc = 0)

array([-15,  12,  -3])

In [26]:
np.cross(a, c, axis = 0)

array([-15,  12,  -3])

In [27]:
m = np.array([ [1, 2, 3], [4, 5, 6] ])

In [28]:
n = np.array([ [4, 5, 6], [1, 2, 3] ])

In [30]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
n

array([[4, 5, 6],
       [1, 2, 3]])

In [32]:
np.cross(m, n)

array([[-3,  6, -3],
       [ 3, -6,  3]])

In [36]:
np.cross(m, n, axis = 0)

array([-15, -21, -27])