In [2]:
from numpy import * 

In [13]:
twoDimArray = arange(11)

In [12]:
twoDimArray

array([], dtype=int32)

# Below show that linspace can have start pos > end pos whereas arange CANNOT have start pos > end pos

In [15]:
linspace(11, 2, 5) 

array([11.  ,  8.75,  6.5 ,  4.25,  2.  ])

In [19]:
twoDimArray = array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

In [21]:
twoDimArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
twoDimArray[1][2]

6

# numpy 2D Array accessing trick

In [26]:
twoDimArray[1, 2]

6

In [27]:
twoDimArray[1]

array([4, 5, 6])

In [28]:
twoDimArray[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
twoDimArray[2:]

array([[7, 8, 9]])

In [31]:
twoDimArray[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
twoDimArray[ : , :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [73]:
twoDimArray[ : , 2]

array([3, 6, 9])

In [74]:
twoDimArray[ 2, :2]

array([7, 8])

In [76]:
twoDimArray[ : : 2, : : 2]

array([[1, 3],
       [7, 9]])

# array [ rows, column] 
# first row splice iteration then complete all possible splice range for column
# next row splice iteration and again all possible splice range for column
# ..............
# this repeats until all all possible splice range for Rows


# it DOES NOT follows first all possible ROWS splice iterations and then all possible COLUMNS splice iterations.