In [2]:
import numpy as np

In [64]:
array = np.arange(0, 21, 2)

In [65]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.linspace(0, 21, 2)

array([ 0., 21.])

In [10]:
array[0]

0

In [66]:
array[-1]

20

In [67]:
array[1]

2

In [68]:
array[-12]

IndexError: index -12 is out of bounds for axis 0 with size 11

In [69]:
array[11]

IndexError: index 11 is out of bounds for axis 0 with size 11

In [70]:
array[:]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
array[6:]

array([12, 14, 16, 18, 20])

In [72]:
array[:6]

array([ 0,  2,  4,  6,  8, 10])

In [75]:
revarray = array[-1:-12:-1]

# trick reverse slice

In [37]:
# array[: :-1]

In [73]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [76]:
revarray

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

In [77]:
revarray[0] = 56

In [78]:
revarray

array([56, 18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

# changes reflected in original array 

In [79]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 56])

# this changes show that in NUMPY LIB another variables actually referencing to original array and DOES NOT create copy of original array in another variable

# # Hence to create copy of original array in another variable use copy methods of NUMPY LIB as shown below  

In [80]:
array


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 56])

In [81]:
copyArray = array.copy()

In [82]:
copyArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 56])

In [84]:
copyArray[:] =  0

In [85]:
copyArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# does not reflect due to copy creation

In [86]:
array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 56])