### To check for neccessary files 

In [1]:
import os
os.listdir()

['.ipynb_checkpoints',
 'CleanupData.csv',
 'Data Preprocessing.html',
 'Data Preprocessing.ipynb',
 'Revision DataPreprocessing.ipynb']

### Import Required Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Load the Dataset

In [3]:
dataFrame = pd.read_csv('CleanupData.csv')

In [4]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   State             10 non-null     object 
 1   Age               9 non-null      float64
 2   Pocket Money      9 non-null      float64
 3   Course Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [5]:
dataFrame

State   Age  Pocket Money Course Purchased
0     Delhi  34.0        7200.0               No
1    Mumbai  17.0        4800.0              Yes
2  Banglore  20.0        5400.0               No
3    Mumbai  28.0        6100.0               No
4  Banglore  30.0           NaN              Yes
5     Delhi  25.0        5800.0              Yes
6    Mumbai   NaN        5200.0               No
7     Delhi  38.0        7900.0              Yes
8  Banglore  40.0        8300.0               No
9     Delhi  27.0        6700.0              Yes

### To create Independent Matrix and Dependent Matrix from dataFrame

In [6]:
X = dataFrame.iloc[ : , :3].values

In [7]:
# Independent Matrix X
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, nan],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', nan, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

In [8]:
y = dataFrame.iloc[ : , 3].values

In [9]:
# Independent Matrix y
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Data preprocessing 

## Step 1 : Handling of Missing Data

In [10]:
from sklearn.impute import SimpleImputer

In [11]:
simpleimputer = SimpleImputer(missing_values=np.NaN, strategy='mean')

In [12]:
simpleimputer.fit(X[ : , 1: 3])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [13]:
X[ : , 1: 3] = simpleimputer.transform(X[ : , 1: 3])

In [14]:
X

array([['Delhi', 34.0, 7200.0],
       ['Mumbai', 17.0, 4800.0],
       ['Banglore', 20.0, 5400.0],
       ['Mumbai', 28.0, 6100.0],
       ['Banglore', 30.0, 6377.777777777777],
       ['Delhi', 25.0, 5800.0],
       ['Mumbai', 28.77777777777778, 5200.0],
       ['Delhi', 38.0, 7900.0],
       ['Banglore', 40.0, 8300.0],
       ['Delhi', 27.0, 6700.0]], dtype=object)

## Step 2 : Handling of Categorical Data

In [15]:
from sklearn.preprocessing import LabelEncoder

In [16]:
labelencoder = LabelEncoder()

In [17]:
X[ : , 0] = labelencoder.fit_transform(X[ : , 0])

In [18]:
X

array([[1, 34.0, 7200.0],
       [2, 17.0, 4800.0],
       [0, 20.0, 5400.0],
       [2, 28.0, 6100.0],
       [0, 30.0, 6377.777777777777],
       [1, 25.0, 5800.0],
       [2, 28.77777777777778, 5200.0],
       [1, 38.0, 7900.0],
       [0, 40.0, 8300.0],
       [1, 27.0, 6700.0]], dtype=object)

## Step 3 : Handling of Categorical label encoded data values priority conflicts

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
onehotencoder = OneHotEncoder()

In [21]:
X_catagorical = X[ : , 0]

In [22]:
X_catagorical

array([1, 2, 0, 2, 0, 1, 2, 1, 0, 1], dtype=object)

In [23]:
X_catagorical = X_catagorical.reshape([10, 1])

In [24]:
X_catagorical 

array([[1],
       [2],
       [0],
       [2],
       [0],
       [1],
       [2],
       [1],
       [0],
       [1]], dtype=object)

In [25]:
X_catagorical = onehotencoder.fit_transform(X_catagorical).toarray()

In [26]:
X_catagorical

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [27]:
Dummy = np.zeros( [10, 5])

In [28]:
Dummy

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
Dummy[ : , : 3] = X_catagorical
Dummy[ : , 3: ] = X[ : , 1: ]

In [30]:
X = Dummy

In [31]:
X

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.40000000e+01,
        7.20000000e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.70000000e+01,
        4.80000000e+03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.00000000e+01,
        5.40000000e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.80000000e+01,
        6.10000000e+03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        6.37777778e+03],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.50000000e+01,
        5.80000000e+03],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.87777778e+01,
        5.20000000e+03],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.80000000e+01,
        7.90000000e+03],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        8.30000000e+03],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 2.70000000e+01,
        6.70000000e+03]])

In [32]:
np.set_printoptions(suppress=True)

In [33]:
X

array([[   0.        ,    1.        ,    0.        ,   34.        ,
        7200.        ],
       [   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ],
       [   1.        ,    0.        ,    0.        ,   20.        ,
        5400.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
        6100.        ],
       [   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778],
       [   0.        ,    1.        ,    0.        ,   25.        ,
        5800.        ],
       [   0.        ,    0.        ,    1.        ,   28.77777778,
        5200.        ],
       [   0.        ,    1.        ,    0.        ,   38.        ,
        7900.        ],
       [   1.        ,    0.        ,    0.        ,   40.        ,
        8300.        ],
       [   0.        ,    1.        ,    0.        ,   27.        ,
        6700.        ]])

In [34]:
# Label encoding of y
y = labelencoder.fit_transform(y)

In [35]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Step 4 : To prepare training and testing data set

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [38]:
X_train

array([[   0.        ,    0.        ,    1.        ,   17.        ,
        4800.        ],
       [   0.        ,    0.        ,    1.        ,   28.        ,
        6100.        ],
       [   0.        ,    0.        ,    1.        ,   28.77777778,
        5200.        ],
       [   0.        ,    1.        ,    0.        ,   38.        ,
        7900.        ],
       [   1.        ,    0.        ,    0.        ,   30.        ,
        6377.77777778],
       [   0.        ,    1.        ,    0.        ,   34.        ,
        7200.        ],
       [   1.        ,    0.        ,    0.        ,   20.        ,
        5400.        ],
       [   1.        ,    0.        ,    0.        ,   40.        ,
        8300.        ]])

In [39]:
y_test

array([1, 1])

## Step 5 (Optional) : Feature Scaling (Standard Deviation or Normalization)

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
X_scale = StandardScaler()

In [42]:
X_train = X_scale.fit_transform(X_train)

In [43]:
X_test = X_scale.transform(X_test)

In [44]:
X_train

array([[-0.77459667, -0.57735027,  1.29099445, -1.65879278, -1.33739326],
       [-0.77459667, -0.57735027,  1.29099445, -0.19580405, -0.25732416],
       [-0.77459667, -0.57735027,  1.29099445, -0.0923604 , -1.00506431],
       [-0.77459667,  1.73205081, -0.77459667,  1.13418571,  1.23815614],
       [ 1.29099445, -0.57735027, -0.77459667,  0.0701939 , -0.02654016],
       [-0.77459667,  1.73205081, -0.77459667,  0.60218981,  0.65658047],
       [ 1.29099445, -0.57735027, -0.77459667, -1.25979585, -0.83889983],
       [ 1.29099445, -0.57735027, -0.77459667,  1.40018366,  1.5704851 ]])

In [45]:
X_test

array([[-0.77459667,  1.73205081, -0.77459667, -0.59480097, -0.50657087],
       [-0.77459667,  1.73205081, -0.77459667, -0.32880302,  0.24116928]])